### ISSUE TITLE
Forgot to close handle somewhere in http client

### ISSUE THREAD

**Issue by artem78** [artem78/s60-maps#1]
Program shutdown with panic CONE 36 "Open handles were found during application shutdown". It occured after downloading tiles with [HTTP client](https://github.com/artem78/s60-maps/blob/67c1fee5c245619df28a963cdb829d8911d891ad/src/HTTPClient.cpp). I checked out source, but found nothing suspicious.

Found on commit 6883bf2065baac0615f9eee623aca2e129f2a9e3.

**Comment by baranovskiykonstantin** [comment]
It seems this issue is emulator-specific. I can't reproduce it on the real device.

**Comment by artem78** [comment]
Do you have empty fille in path ``c:\resource\errrd`` on your phone? Otherwise you can\`t see panic messages.

**Comment by baranovskiykonstantin** [comment]
Yes, I have. Also I ran the app on the device in debug mode from Carbide and it closed successfully without any messages.

**Comment by artem78** [comment]
I recorded video from emulator how to reproduce: [link](https://yadi.sk/i/KwJfiwbOQfQHog)

Need to test on my phone.

**Comment by baranovskiykonstantin** [comment]
My emulator also panics (CONE 36) on exiting if httpclient has been used but the real device (Nokia 5530) does not.

**Comment by artem78** [comment]
> It seems this issue is emulator-specific

Looks that you are right. I just tested last release and debug build on my phone (Nokia N95 8Gb) and there is no this problem. I\`s good.

**Comment by artem78** [comment]
Anyway thank you for help.
