### ISSUE TITLE
Current map not ticked in menu

### ISSUE THREAD

**Issue by artem78** [artem78/s60-maps#13]
If you go to `Maps` submenu, you may see that current item not always ticked. I don\`t know what may be the reason.

![GifTailor_0002](https://user-images.githubusercontent.com/8585304/103206476-014a9680-490d-11eb-8aa3-66f732f937e5.gif)

I discovered this issue only on real phone (N95 8Gb), but don\`t see it on emulator from SDK.

Program version: 1.1.0 (latest)

**Comment by fizolas** [comment]
For the record, the issue also occurs in an E63 and an E72.

**Comment by artem78** [comment]
Could you please check if problem is solved: [S60Maps_a2852707.zip](https://github.com/artem78/s60-maps/files/6454583/S60Maps_a2852707.zip)

**Comment by fizolas** [comment]
Hi Artem,

The issue is gone in my E72, good job!

**Comment by artem78** [comment]
Fixed in v1.4.0
