### ISSUE TITLE
Unknown classes

### ISSUE THREAD

**Issue by baranovskiykonstantin** [artem78/s60-maps#14]
The build is broken with S60 5th SDK because of unknown classes:

CFileTreeMapper https://github.com/artem78/s60-maps/blob/master/inc/Map.h#L264

TDirStats https://github.com/artem78/s60-maps/blob/master/src/S60MapsAppUi.cpp#L501

FileUtils::DirectoryStats() https://github.com/artem78/s60-maps/blob/master/src/S60MapsAppUi.cpp#L507

Cannot find any information about them neither in the sdk documentation nor in the web.
It looks like some files are not in the latest condition or missing.

**Comment by artem78** [comment]
There are my own classes and they located in [FileUtils module](https://github.com/artem78/s60-file-utils).

**Comment by artem78** [comment]
After [your pull request](https://github.com/artem78/s60-maps/pull/12) it must works.

**Comment by artem78** [comment]
Check if `modules/FileUtils` directory exists. If no, update submodules.

**Comment by artem78** [comment]
I fixed this!

I forgot to push some last changes from FileUtils module. Try now.

**Comment by baranovskiykonstantin** [comment]
OK, now it builds and works. I'm closing this issue.
