### ISSUE TITLE
Hebrew translation.

### ISSUE THREAD

**Issue by Men770** [artem78/s60-maps#15]
I want to translate the application into Hebrew, how can I do that?
Thanks.

**Comment by artem78** [comment]
First, I need to add multilanguage support for the application and move all strings to localization files. After that you will be able to edit strings for your language.

**Comment by artem78** [comment]
May be I will do it soon.

**Comment by Men770** [comment]
This is all strings:
Follow me -  עקוב אחרי
Maps - מפות
Service - כלים
Map cache statistics - סטטיסטיקות מטמון מפה
Clear map cache - ניקוי מטמון מפה
About - אודות
About text - S60Maps גירסא %0U\nזמן: " __DATE__ " " __TIME__ "\nגיט: %1U %2U\nיוצר: artem78 (megabyte1024@ya.ru)\nאתר: https://github.com/artem78/s60-maps\nתודות: baranovskiykonstantin, Symbian9

**Comment by misheu12** [comment]
Can't translate the r01 file? (I did not unpack the SIS)

**Comment by artem78** [comment]
No need to unpack sis-package. I will add r-file for your language tomorrow, so you can edit it.

**Comment by misheu12** [comment]
thank you!
I will translate into Hebrew, @Men770 .

**Comment by artem78** [comment]
I just added file for Hebrew in `localization` branch - [S60Maps.l57](https://github.com/artem78/s60-maps/blob/localization/data/S60Maps.l57).

Before commit make sure that file saved in **UTF8 charset without BOM**. Also you may add yourself in `Author` section.
