### ISSUE TITLE
Application fails to start randomly

### ISSUE THREAD

**Issue by fizolas** [artem78/s60-maps#18]
Sometimes the application fails to start for a few times in a row. The error message (after creating the empty file c:\Resource\errrd to activate the error messages) is "Application closed: S60Maps KERN-EXEC 3".

After a few failed tries, the application eventually starts. It also starts correctly after the cache e:\Data\S60Maps is deleted.

**Comment by artem78** [comment]
Try to install and run last debug build: [S60Maps debug eabf60b.zip](https://github.com/artem78/s60-maps/files/5939478/S60Maps.debug.eabf60b.zip)

After program fails, attach log which located in `e:\data\s60maps\s60maps_log.txt`.

**Comment by artem78** [comment]
What map service you use? Sometimes application may fails when used different map from OpenStreetMap.

Tip: If program fails to start you may try to delete settings file `store.dat` instead of clear full cache.

**Comment by fizolas** [comment]
The issue happens with all four maps, as far as I can see. Deleting store.dat definitely helps: the application starts smoothly after deleting this file. 

I am attaching four different logs obtained with the debug build you made available above. All logs were produced running S60maps on an E72. I hope they are of help!

[s60maps_log.txt](https://github.com/artem78/s60-maps/files/5961112/s60maps_log.txt)
[s60maps_log2.txt](https://github.com/artem78/s60-maps/files/5961114/s60maps_log2.txt)
[s60maps_log3.txt](https://github.com/artem78/s60-maps/files/5961115/s60maps_log3.txt)
[s60maps_log4.txt](https://github.com/artem78/s60-maps/files/5961116/s60maps_log4.txt)

**Comment by artem78** [comment]
Sorry, but I forgot that with current settings logger uses buffered output. Therefore when application terminates with panic, log may be incomplete.

Although according to available information seems this is known bug and more info not required yet.

**Comment by artem78** [comment]
Hello, @fizolas. Sorry to keep you waiting, because I have not enough free time.

I made some changes. Try this: [S60Maps_9fb490e.zip](https://github.com/artem78/s60-maps/files/6031494/S60Maps_9fb490e.zip).

I realized that my sources is very messy and tangled. Therefore it is quite expected that program sometimes fails in different places. Code refactoring is needed, but I don\`t know when I will make this.

**Comment by fizolas** [comment]
Hi Artem, 

The real s60v3 diehards don't mind waiting at this point :) Thank you very much to you for all the time and effort you have put into this great project!  

I installed the new test version above, and things seem to be now working very well. The application does not fail to start anymore, and tile loading times are fast. Also, switching among maps seems quicker.

**Comment by artem78** [comment]
Hi Fizolas!

Today I released [new version](https://github.com/artem78/s60-maps/releases/tag/v1.3.0) of S60Maps which includes fixes of recently discovered problems. For your help for the project I added you to the "thanks-list" in program "About" window.

Now I will close this issue, but if you will discover more unexplained crashes you may reopen it or create new one.
