### ISSUE TITLE
Unable to change zoom using volume keys

### ISSUE THREAD

**Issue by artem78** [artem78/s60-maps#2]
I have volume keys on my Nokia N95 8gb and want to use them for zoom changing in addition to keys `1` and `3`.

I think `EStdKeyIncVolume` and `EStdKeyDecVolume` is right scan codes for these keys, but unfortunately for some unknown reason threre are no any key pressed events in `OfferKeyEventL` when I pressed these key. I tried to add more input capabilities (`ENavigation` and others) in `InputCapabilities()` method, but no effect.

My test commit: d49d15818f130ba5ffefb8d10747f78c42878931

Hope anybody can tell me, what is wrong. Thanks.

**Comment by Symbian9** [comment]
Maybe, here is related info:

- https://github.com/mobbler/mobbler/issues/525
- https://wiki.qt.io/Audio_Volume_Key_Event_On_Symbian

FTR, Also, take a look on this: https://github.com/RomanSaveljev/KeypadBuddy

**Comment by artem78** [comment]
Code from QT example works fine on my phone (don\`t know about others). Thanks a lot.

By the way, why remote api used in general?

**Comment by Symbian9** [comment]
> By the way, why remote api used in general?

I don't know.
