### ISSUE TITLE
Add source tarballs assets for releases

### ISSUE THREAD

**Issue by Symbian9** [artem78/s60-maps#29]
Actually release tarballs (autogenerated `*.zip`/`*.tar.gz` by GitHub) does not incude all modules sources.

Add source tarballs (`*.tar.gz` with all modules source included) as assets to releases.

**Comment by artem78** [comment]
All modules attached to this project as git submodules in [/modules/](https://github.com/artem78/s60-maps/tree/master/modules) directory. All of them located on GitHub and have public access. After you cloned repository you need to load all submodules too with command `git submodule update --init`. Another way is run `clone` command with `--recursive` option.

**Comment by artem78** [comment]
> *.tar.gz

Why not zip? It is more popular.

**Comment by Symbian9** [comment]
> Why not zip? It is more popular.

Or ZIP ;)

**Comment by artem78** [comment]
Added in zip for v1.4.0.

Is it actually needed for anybody?

**Comment by artem78** [comment]
@Symbian9 Fixed. You are very attentive.
