### ISSUE TITLE
Cached on disk tiles display in Gallery

### ISSUE THREAD

**Issue by artem78** [artem78/s60-maps#3]
Downloaded map tiles stored on disk in Symbian MBM format. Therefore, they are displayed in the Gallery with others images saved on phone:

![Snap3482](https://user-images.githubusercontent.com/8585304/84695865-33d60880-af54-11ea-8b35-e2a904221fed.jpg)

I tried to change file extension to something like `.dat` or drop it at all, but in any case system detect that it is image file and show it in gallery. Make cache directory hidden also did not give any effect.

Is there any solution except using some own file format?

**Comment by Symbian9** [comment]
> Is there any solution except using some own file format?

Yes!

Symbian OS has a smart trick: *"Gallery"* ignore to index images (and not generate thumbnails) for images placed inside folders named as `_PAlbTN` or its sub-folders.

So, just store "S60Maps" cached tiles in folder like: `<disk>:\<S60Maps_folder>\_PAlbTN\<cache_folders_structure>\<tile_images>`

This trick used by "ViewRanger](https://www.viewranger.com/software/software.php)" app where its cache stored in `C:\ViewRanger\MapCache\_PAlbTN\<cache_folders_structure>\<tile_images>`

I highly recommends you to grab *"ViewRanger"*  `v2.9.5` app for Symbian (actually freeware; no further development):

- S60 3rd edition, keypad phones - https://www.viewranger.com/software/software.php?type=SYMBIAN3
  - direct link - http://www.viewranger.com/software/ViewRanger3rdEd.sisx
- S60 5th edition, ^3, Anna or Belle touch screen phones - https://www.viewranger.com/software/software.php?type=SYMBIAN5
  - direct link - http://www.viewranger.com/software/ViewRanger5thEd.sisx

### REFERENCE
- ViewRanger on OSM Wiki (in Russian) - https://wiki.openstreetmap.org/wiki/RU:ViewRanger_GPS#.D0.9E.D0.BF.D0.B8.D1.81.D0.B0.D0.BD.D0.B8.D0.B5_.D1.81.D1.82.D1.80.D1.83.D0.BA.D1.82.D1.83.D1.80.D1.8B_.D1.84.D0.B0.D0.B9.D0.BB.D0.B0
  - **MUST READ:** `sasgis-ViewRanger.pdf` (docs written by me on ViewRanger file formats & file structure) - http://www.sasgis.org/mantis/file_download.php?file_id=1955&type=bug
- https://www.viewranger.com/software/software.php
  - `ViewRanger_user_manual.pdf` - http://www.viewranger.com/manuals/ViewRanger_user_manual.pdf
- http://www.allaboutsymbian.com/reviews/item/ViewRanger.php

**Comment by artem78** [comment]
> Symbian OS has a smart trick: _"Gallery"_ ignore to index images (and not generate thumbnails) for images placed inside folders named as `_PAlbTN` or its sub-folders.

Thanks! Simple solution and it works.

> ViewRanger
I will have a look at it, but for me more useful is to see it\`s source code. Are you have to take part in it\`s development?

**Comment by Symbian9** [comment]
> Are you have to take part in it`s development?

Sadly, no.

I use *ViewRanger* app for personal purpose (as mobile alternative to SAS.Planet) and documented mostly all formats & file structure.

FTR, Just asked to open-source it:

- https://twitter.com/app4soft/status/1272907095868944389

P.S.: Has you digged into "Symbian Sources" repo (there are various mirrors) for original Symbian location/map related code? For example:

- https://github.com/SymbianSource/oss.FCL.sf.app.location/branches

**Comment by artem78** [comment]
> Has you digged into "Symbian Sources" repo

No. Thank you for the link.
