### ISSUE TITLE
Add build instruction

### ISSUE THREAD

**Issue by Symbian9** [artem78/s60-maps#30]
Add `COMPILING.md` with a step-by-step instruction how to build app from source.

**Comment by WunderWungiel** [comment]
Yeah, I also want it :+1:

**Comment by artem78** [comment]
Added [docs/COMPILING.md](https://github.com/artem78/s60-maps/blob/master/docs/COMPILING.md). Sorry for too long waiting.

**Comment by Symbian9** [comment]
Thanks!
