### ISSUE TITLE
Finding landmarks in a faster way (possible usability improvement?)

### ISSUE THREAD

**Issue by fizolas** [artem78/s60-maps#49]
Hi Artem,

When one has lots of landmarks (say thousands), it takes a long time to locate a particular one to get it displayed in S60Maps. 

I was wondering whether some kind of speed up technique could be implemented to find a landmark faster. The idea would be to list all landmarks first (as it happens now). If you then type "a", only landmarks starting with "a" or "A" (or even better, landmarks having words starting with "a" or "A") would appear in the list. If you then type "b", only landmarks with words starting with "ab", "AB", "Ab" or "aB" would be listed, etc. In this way one would quickly narrow down the landmark list.

This is the way a few s60v3 apps such as AppQLaunch,  Handy Taskman, or MagicKey narrow down long lists of elements, and it works quite well.

Best regards.

**Comment by artem78** [comment]
Hi Fizolas!

I agree that it is important feature. By the way landmarks list was implemented by another person and [I suggest to him the same improvement](https://github.com/artem78/s60-maps/pull/35#issuecomment-984447416). But he has not enought spare time to make this.

**Comment by artem78** [comment]
Hi @fizolas!

I have implemented search in landmarks list. Please test it: [S60Maps_search_in_landmarks.zip](https://github.com/artem78/s60-maps/files/8549494/S60Maps_search_in_landmarks.zip)

Start typing for make search field visible. I think it will be better to make search field visible permanently (like in phone's contact book), but I don't understand how to make this.

**Comment by fizolas** [comment]
Hi Artem! I just tried it and it works great. The search works perfectly both with the Latin and the Greek alphabets (I have quite a few landmarks in Greek...) I don't think you need to make the search field permanently visible, as typing instead of scrolling is a natural thing to do when presented with a list. Your implementation works just like the one in Handy Taskman, for example.
