### ISSUE TITLE
Small usability improvement

### ISSUE THREAD

**Issue by fizolas** [artem78/s60-maps#51]
Hi Artem,

The last search improvement really has been great for the usability of S60maps. 

When panning around a map (i.e. up, down, left, right with the joystick) it is rather easy to unwittingly hit the central button (i.e. "ok") with some phones. For example, this happens all the time with the E52 (in other phones, such as the E72, the central button is a bit deeper and so this happens more rarely).

The default behaviour when hitting "ok" is setting/editing a landmark, which is rather annoying because it means having to press "cancel" every time the above mistake happens.

Would it be possible to change the key for setting/editing landmarks from "ok" to, say, "5"?

All the best!

**Comment by artem78** [comment]
> Would it be possible to change the key for setting/editing landmarks from "ok" to, say, "5"?

Okay, I'll change it.

> would it be possible to "prefill" the landmark name when setting a landmark?

I can add feature for saving search results as landmarks. Thank you for the idea.

-----------

**_P.S.:_** Next time could you please post your questions/problems/ideas as separate issues? This helps me to organize them and marks finished. Thanks.

**Comment by fizolas** [comment]
Hi Artem,

I have edited this issue and put the second suggestion as a separate issue, as you asked.

Kind regards

**Comment by artem78** [comment]
Done in v1.9.1
