### ISSUE TITLE
Requested application access not granted

### ISSUE THREAD

**Issue by caspargross** [artem78/s60-maps#58]
Hi!

The installation fails on a rooted Nokia E75 with the error "Requested application access not granted" 

The installation process does not ask for acess, this step works for other apps.

Somebody has an idea how to solve this?
Thanks, Caspar

**Comment by fizolas** [comment]
In "Application Manager", have you set "Software Installation" to "All" and "Online certificate check" to "Off"?

**Comment by caspargross** [comment]
Thanks, that solved it!
