### ISSUE TITLE
Add more screenshots

### ISSUE THREAD

**Issue by Symbian9** [artem78/s60-maps#6]
Add few more screenshots of *S60Maps* `v1.0.0` UI into `README.md`:

- S60Maps launch icon in application list;
- Main window;
- Settings window;
- About window;
- etc.

**Comment by artem78** [comment]
I can make this when I have enought free time. Why do you want screenshots of every window? I think, this is overmuch.

**Comment by Symbian9** [comment]
> Why do you want screenshots of every window?

To be clear, I just ask for few more screenshots which would show app UI, as current GIF in `README.md` show nothing than map tiles & moving arrow.

**Comment by artem78** [comment]
Current UI is simple and do not have much items:

![Snap3536](https://user-images.githubusercontent.com/8585304/100780090-5aaccc00-341a-11eb-8eab-3107d619001b.png) ![Snap3537](https://user-images.githubusercontent.com/8585304/100780092-5bddf900-341a-11eb-876a-bf7f4ea742f2.png) ![Snap3539](https://user-images.githubusercontent.com/8585304/100780095-5c768f80-341a-11eb-906e-3af663b19213.png) ![Snap3538](https://user-images.githubusercontent.com/8585304/100780093-5bddf900-341a-11eb-82f0-e9348e663acf.png)

**Comment by artem78** [comment]
> Settings window

I didn\`t started to make this yet.

**Comment by Symbian9** [comment]
> [About dialog](https://user-images.githubusercontent.com/8585304/100780093-5bddf900-341a-11eb-82f0-e9348e663acf.png)

This one is nice!

**Comment by artem78** [comment]
> I will try to recover my N82 (need play with power supply to launch it, as battery is lost) and maybe would provide some more screenshots.

Good luck!

**Comment by artem78** [comment]
Please have a look at updated readme. Also I plan in the future to add some video recordings.

**Comment by Symbian9** [comment]
> Please have a look at updated readme.

Thanks!

> Also I plan in the future to add some video recordings.

Would be great!

Has you tried to launch *S60Maps* app in Symbian emulator? (aka *EKA2L1*)

- https://github.com/EKA2L1/EKA2L1

**Comment by artem78** [comment]
> Has you tried to launch _S60Maps_ app in Symbian emulator? (aka _EKA2L1_)

No. Why?

> JFTR, Here are all versions of the _GifTailor_ screen-recorder app for Symbian 9.x:

I already installed it yesterday. I have one question about it:  is it possible to record screen as movie file, not gif?

**Comment by Symbian9** [comment]
> For what is it needed, if it works on phone?

For testing that emulator works as real device.

> I have one question about it: is it possible to record screen as movie file, not gif?

I'm not sure (not used it for a while), but as I remember there was option in GifTailor shoot series of screenshots with minimal interval - so, "record screencast" as series of multiply PNGs (`01.png`, `02.png`,...) & import as sequence (set of frames) in video editor such as Olive (https://github.com/olive-editor/olive), then just export as video.

Recording real video screencast directly on device may decrease performance — instead it would be better stream screen via VNC or something like that to PC.

P.S. I will try find some info on video recording.

**Comment by artem78** [comment]
> Has you tried to launch _S60Maps_ app in Symbian emulator?

I will try and let you know about result.

> instead it would be better stream screen via VNC or something like that to PC.

But this is impossible when outdoors.

> P.S. I will try find some info on video recording.

Thank you.

**Comment by artem78** [comment]
Today I two times tried to record video outdoors with GifTailor, but unsuccessfully. First time my phone went to reboot after 2-3 minutes of recording. Next time it silently closed with S60Maps after the similar period of time. Seems that GifTailor not supports long recording.

Besides, I didn’t find how to get separate frames images instead of complete GIF file.

**Comment by artem78** [comment]
> Has you tried to launch _S60Maps_ app in Symbian emulator? (aka _EKA2L1_)

I spent much time trying to launch emulator on my computer. Unfortunately S60Maps doesn\`t work with it. But I\`m not sure if it is application specific or emulator problem.

![Screenshot_2020-12-06_09-50-36](https://user-images.githubusercontent.com/8585304/101277039-80432800-37c2-11eb-85ab-38c5919921de.png)

Log: [EKA2L1 (1).log](https://github.com/artem78/s60-maps/files/5648560/EKA2L1.1.log)

**Comment by artem78** [comment]
> > Also I plan in the future to add some video recordings.
> 
> Would be great!

I was able to make screen recording of several minutes length today!
https://github.com/artem78/s60-maps#and-video

**Comment by Symbian9** [comment]
> I was able to make screen recording of several minutes length today!

Great!
