### ISSUE TITLE
Add app info into OSM Wiki

### ISSUE THREAD

**Issue by Symbian9** [artem78/s60-maps#7]
Add *S60Maps* info into OSM Wiki (requires OSM account)

- [x] https://wiki.openstreetmap.org/wiki/S60Maps (article)
- [x] https://wiki.openstreetmap.org/wiki/Symbian (comparison)

**Comment by artem78** [comment]
Is it really needed for old and abandoned platform?

**Comment by Symbian9** [comment]
> Is it really needed for old and abandoned platform.

Yes. As a lot of Symbian devices still in use it would be good to represent new apps

- https://old.reddit.com/r/symbian/new/
  - https://old.reddit.com/r/symbian/comments/k1png1/s60maps_100_yet_another_maps_app_for_symbian_os/
  - https://old.reddit.com/r/symbian/comments/j0zaoj/scummvm_220_testing_out/
- https://old.reddit.com/r/openstreetmap/new/

**Comment by artem78** [comment]
> As a lot of Symbian devices still in use

Nice to hear this. My N95 8Gb phone is 12 years old, but still works and I use it. But in real life I never see that someone use them.

> Add _S60Maps_ info into OSM Wiki (requires OSM account)

I will think about it. Of course, I have OSM account. But write articles and descriptions is not easy for me. Maybe because English is not my native language I don't know him well.

**Comment by Symbian9** [comment]
> But in real life I never see that someone use them.

There are a lot active Symbian users on `r/Symbian` and on Twitter ;-)

- https://twitter.com/ssingh4893/status/1277238063668711424
- https://twitter.com/rubenpirate/status/1278267367265533959
- https://twitter.com/nakor25/status/1311514110090072064
- https://twitter.com/BlazPotocnik97/status/1325153025476812800
- https://twitter.com/theMrMobile/status/1323702223759659009
- https://twitter.com/ota024/status/1323717836561408000
- https://twitter.com/danialiqbal_/status/1308029820631044097
- https://twitter.com/TeslaOwnersLV/status/1323860893310935040
- https://twitter.com/rcstyle1/status/1324856721961967616
- https://twitter.com/ampressman/status/1325065679863750656
  - https://twitter.com/theMrMobile/status/1286048758371954695
    - https://youtu.be/AUsEmeVOra8

**Comment by artem78** [comment]
I started to add information in OSM wiki. I want to add screenshot, but can\`t upload any file.
![20201205_220144](https://user-images.githubusercontent.com/8585304/101261157-2bfa6280-3746-11eb-8c0f-d21842895412.png)

Maybe you know how to fix this?

**Comment by Symbian9** [comment]
> Maybe you know how to fix this?

I'm not logged into OSM Wiki for a while, so can't say nothing about this "permission" issue.

Guess, it would be much better ask this question on OSM Forum

- https://wiki.openstreetmap.org/wiki/Forum

**Comment by artem78** [comment]
As far as I understand, comparison table will be updated automatically, but so far S60Maps didn\`t appear in it. I don\`t know why.

**Comment by Symbian9** [comment]
Guess, if so, just need ask on OSM Forum.

**Comment by artem78** [comment]
Seems that bot, which updates this table is offline since 2014.

![Снимок экрана в 2020-12-20 17-12-59](https://user-images.githubusercontent.com/8585304/102715466-b3b7a380-42e6-11eb-8507-09b72cb41721.png)


https://wiki.openstreetmap.org/wiki/User:TTTBot
https://github.com/tordanik/TemplatesToTables/issues/6

**Comment by Symbian9** [comment]
> Seems that bot, which updates this table is offline since 2014.

I can't say nothing about this issue.

You should try connect OSM Dev Team via Forum, IRC or Twttier.

**Comment by artem78** [comment]
I just informed you. No any help from your side is needed. :)

**Comment by Symbian9** [comment]
> No any help from your side is needed. :)

BTW, I'm interested in what has happen with OSM Wiki.

**Comment by artem78** [comment]
As I was told on the forum, currently there are no mechanizm to automatically update table and I need to edit it manually.
[https://forum.openstreetmap.org/viewtopic.php?id=71474](https://forum.openstreetmap.org/viewtopic.php?id=71474)
